version: '3'

services:
  weather_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    ports:
      - "9090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - weather_app

