name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Extract Git commit hash
        id: get_commit
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/weather_argo:${{ env.COMMIT_HASH }}

      - name: Checkout second repository
        uses: actions/checkout@v2
        with:
          repository: Denisiuss/manifests-for-ArgoCD
          token: ${{ secrets.TOKKEN_GITH }}
          path: argocd-repo

      - name: Update Kubernetes manifest
        run: |
          sed -i 's|image: .*$|image: '"${{ secrets.DOCKER_USERNAME }}/weather_argo:${{ env.COMMIT_HASH }}"'|' argocd-repo/deployment.yaml

      - name: Commit and push changes
        run: |
          cd argocd-repo
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Update Docker image to latest'
          git push

